#!/usr/bin/env bash
#
# daily cron job for the dirvish package
#
if [ ! -x /usr/sbin/dirvish-expire  ]; then exit 0; fi
if [ ! -s /etc/dirvish/master.conf ];  then exit 0; fi


# Help text
usage() {
cat << EOF

Usage: dirvish-cronjob

EOF
}

# Check root privileges
if [ "$(id -u)" -ne 0 ]
then
    echo "This script needs to be run with root privileges" 1>&2
    exit 1
fi

# Ensure only one instance is running at a time
instances=$(pgrep -f -c /usr/sbin/dirvish)
if (( $instances > 1 ))
then
    echo "Dirvish is already running (instances: $instances). Stop."
    exit 1
fi

# Locate mandatory commands
DIRVISH_TIDY=$(command -v dirvish-tidy)
DIRVISH_EXPIRE=$(command -v dirvish-expire)
DIRVISH_RUNALL=$(command -v dirvish-runall)

# Fetch location of local system folders
IFS=:
read LOGDIR _ <<< "$(systemd-path system-state-logs)"
unset IFS

# Add aplication subfolders
LOGDIR+="/dirvish"

# Echo line with preceding timestamp
echotime() { echo "$(date +'%b %d %T'):" "$1" | tee --append "$LOGDIR/dirvish-cronjob.log"; }

# Fetch dirvish bank from /etc/dirvish/master.conf
BANK=$(sed -n '/^bank:/{n;p;}' /etc/dirvish/master.conf | awk '{$1=$1; print}')

# Check dirvish bank
if [ -z "$BANK" ]
then
    echotime "Dirvish bank not defined"
    exit 2
else
    echotime "Default dirvish bank is $BANK"
fi

# Check mount status of backup partition
if findmnt --mountpoint "$BANK" >/dev/null
then
    MOUNTSTAT=0
    echotime "Dirvish device already mounted"
else
    MOUNTSTAT=1
    echotime "Dirvish device not mounted"
fi

# Function to mount dirvish bank unless mounted
mountnow() {
    if ! findmnt --mountpoint "$1" >/dev/null
    then
        MOUNTSTAT=2
        echotime "Mounting dirvish bank ..."
        mount "$1" || exit 1
    fi
}

# Mount Dirvish bank unless mounted
mountnow "$BANK"

# Prune failed backup images
if [ -x "$DIRVISH_TIDY" ]
then

    echotime "Pruning failed backup images ..."
    "$DIRVISH_TIDY"
    RC=$?
    if [ "$RC" -ne 0 ]
    then
        echotime "Failed to run $DIRVISH_TIDY (exitcode: $RC)"
        exit "$RC"
    fi

else

    echotime "Pruning failed backup images ... failed, dirvish-tidy not executable"

fi

# Remove expired backup images
if [ -x "$DIRVISH_EXPIRE" ]
then

    echotime "Removing expired backup images ..."
    "$DIRVISH_EXPIRE" --quiet
    RC=$?
    if [ "$RC" -ne 0 ]
    then
        echotime "Failed to run $DIRVISH_EXPIRE (exitcode: $RC)"
        exit "$RC"
    fi

else

    echotime "Removing expired backup images ... failed, dirvish-expire not executable"

fi

# Runall dirvish vaults
if [ -x "$DIRVISH_RUNALL" ]
then

    echotime "Creating new backup images ..."
    "$DIRVISH_RUNALL" --quiet
    RC=$?
    if [ "$RC" -ne 0 ]
    then
        echotime "Failed to run $DIRVISH_RUNALL (exitcode: $RC)"
    fi

else

    echotime "Creating new backup images ... failed, dirvish-runall not executable"

fi

# Umount backup partition if unmounted before
if [ "$MOUNTSTAT" -eq 2 ]
then
    echotime "Unmounting dirvish bank ..."
    umount "$BANK" || exit 1
fi

# User message
echotime "Dirvish cronjob completed."

# Terminate successfully
exit 0
